config/routes.rb
Rails.application.routes.draw do
 
  resources :posts, :only=> [:show, :index] do 
  	resources :comments
  end


  namespace :admin do
  	resources :posts
  	resources :categories, :except => [:show]
  end

  root :to => "pages#index"
  get "pages/index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, :dependent => :destroy
	has_and_belongs_to_many :categories

	belongs_to :user

	validates_presence_of  :title, :excerpt, :body, :slug
	validates_uniqueness_of :slug
	validates_inclusion_of :draft, :in => [true, false]  
	validates_associated :user

	  scope :published, lambda { 
	    where("draft = ? AND published_at < ?", false, Time.current)
	  }
	  
	  scope :search, lambda { |terms| 
	     where("title LIKE :t OR body LIKE :t", :t => "%#{terms}%")
	  }
	  
	  def to_param
	    "#{id}-#{slug}"
	  end

	protected
	  def generate_slug
	    self.slug = title unless slug.present?
	    self.slug = slug.parameterize
	  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :list_resources, only: [:show, :edit, :update, :new, :create]


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    respond_with @posts, :location => admin_posts_path
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  	render :location=>"application"
  end

  # GET /posts/new
  def new
    @post = Post.new
    respond_with @post
  end

  # GET /posts/1/edit
  def edit

  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    flash[:notice] = 'Post was successfully created.' if @post.save
    respond_with @post, :location => admin_posts_path
   
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    params[:post][:category_ids] ||= []
flash[:notice] = 'Post was successfully updated.' if @post.update_attributes(post_params)
    respond_with @post, :location => admin_posts_path
   
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_with @post, :location => admin_posts_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :excerpt, :body, :user_id, :slug, :draft, :published_at, category_ids: [])
    end

    def list_resources
      @users = User.all
      @categories = Category.all
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_categories, :only => %w(show index)

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where(nil)
    @posts = @posts.search(params[:search]) if params[:search].present?
    @posts = @category.posts if @category.present?
    @posts = @posts.published

    respond_with @posts
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.published.find(params[:id])
    respond_with @post
  end

protected
  def load_categories
     @categories = Category.all
    @category = Category.find(params[:category_id]) if params[:category_id]
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.erb
<%= form_for [:admin, @post] do |f| %>
  <%= error_messages_for @post %>

  <div id="body">
    <div class="field">
      <%= f.label :user_id, "Post by: " %>
      <%= f.collection_select :user_id, @users, :id, :full_name %>
    </div>

    <div class="field">
      <%= f.text_field :title, :placeholder => "Title", :class => "title" %>
    </div>

    <div class="field">
      <%= f.text_area :excerpt, :placeholder => "Excerpt", :rows => 5, :cols => 70 %>
    </div>

    <div class="field">
      <%= f.text_area :body, :placeholder => "Body", :rows => 30, :cols => 70 %>
    </div>

    <div class="field">
      <%= f.check_box :draft %>
      <%= f.label :draft, "Save as Draft" %>
    </div>

    <hr class="thick" />

    <p>
      <%= f.submit :class => "button" %> or <%= link_to "cancel", admin_posts_path %>
    </p>
  </div>

  <div id="sidebar">
    <%= section "Publish with these categories" do %>
      <ul class="categories-field">
        <%- @categories.each do |c| -%>
          <li><%= check_box_tag "post[category_ids][]", c.id, @post.categories.include?(c) %> <%= c.name %></li>
        <%- end -%>
      </ul>
      <div class="bar">
        <%= link_to "New category", new_admin_category_path, :class => "button right" %>
      </div>
      <br/>
    <% end %>

    <hr/>
    <%= section  do %>
      <div class="field">
        <%= f.label :published_at %><br/>
        <%= f.date_select :published_at, :use_short_month => true %>
      </div>
    <% end %>

    <hr/>
    <%= section do %>
      <div class="field">
        <%= f.label :slug %><br/>
        <%= f.text_field :slug, :size => 27 %>
      </div>
    <% end %>
  </div>

<% end %>

app/views/admin/posts/edit.html.erb
  Editing post
  <%= link_to 'Preview', [:admin, @post], :class => "button right", :target => "_blank" %>
</h2>

<%= render 'form' %>

app/views/admin/posts/index.html.erb
<h2>Posts</h2>

<%- if @posts.present? -%>
<ul class="list">
  <% @posts.each do |post| %>
    <%= content_tag_for :li, post, :class => cycle(:odd, :even) do %>
      <%= link_to post.title.titleize, [:admin, post] %>

      <div class="right">
        <%= link_to_edit [:edit, :admin, post] %>,
        <%= link_to_destroy [:admin, post] %>
      </div>
    <% end %>
  <% end %>
</ul>
<%- else -%>
  <p>You don't have any posts yet.</p>
<%- end -%>

<hr class="thick" />

<div class="bar">
  <div class="right">
    <%= link_to 'New Post', new_admin_post_path, :class => "button" %>
  </div>
</div>

app/views/admin/posts/new.html.erb
<h2>New post</h2>

<%= render 'form' %>

app/views/admin/posts/show.html.erb
<div id="column1">

  <h2><%= @post.title %></h2>

  <div id="post">
    <%= simple_format @post.body %>
  </div>

  <hr/>

 
</div>